=== JaJuMa-GmbH/power-toys/etc/jajuma_powertoys.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2023 JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
-->

<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="urn:magento:module:Magento_Widget:etc/types.xsd"/>

    <xs:annotation>
        <xs:documentation>Contains powertoys.</xs:documentation>
    </xs:annotation>

    <xs:element name="powertoys">
        <xs:annotation>
            <xs:documentation>A list of toys.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element name="quickaction" type="quickactionType" />
                <xs:element name="dashboard" type="dashboardType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="quickactionType">
        <xs:annotation>
            <xs:documentation>Definition of a quick action</xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="label" type="translatableType" />
            <xs:element name="description" type="translatableType" />
            <xs:element type="argumentsType" name="arguments" />
        </xs:all>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="class" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="dashboardType">
        <xs:annotation>
            <xs:documentation>Definition of a dashboard</xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="label" type="translatableType" />
            <xs:element name="description" type="translatableType" />
        </xs:all>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="class" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="bookmarkType">
        <xs:annotation>
            <xs:documentation>Definition of a bookmark</xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="label" type="translatableType" />
            <xs:element name="description" type="translatableType" />
        </xs:all>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="class" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="translatableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="translate" use="optional" fixed="true" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="argumentsType">
        <xs:sequence>
            <xs:element name="argument" type="argumentType" minOccurs="1" maxOccurs="unbounded">
                <xs:key name="argumentItemName">
                    <xs:selector xpath="item" />
                    <xs:field xpath="@name" />
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="argumentType" abstract="true" mixed="true">
        <xs:attribute name="name" use="optional" />
    </xs:complexType>
</xs:schema>

=== JaJuMa-GmbH/power-toys/etc/jajuma_powertoys.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2023 JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
-->

<powertoys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Jajuma_PowerToys:etc/jajuma_powertoys.xsd">

<!--    Example quick action-->
    <quickaction id="example_quickaction" class="Jajuma\PowerToys\Block\PowerToys\QuickAction">
        <label translate="true">Example quick action</label>
        <arguments>
            <argument name="enable">false</argument>
            <argument name="action_type">popup</argument>
            <argument name="template">Jajuma_PowerToys::default_templates/quickaction.phtml</argument>
            <argument name="magewire"></argument>
            <argument name="lazyload">false</argument>
            <argument name="cache_lifetime">0</argument>
            <argument name="sort_order">0</argument>
            <argument name="acl_resource"></argument>
        </arguments>
    </quickaction>

<!--    Example dashboard-->
    <dashboard id="example_dashboard" class="Jajuma\PowerToys\Block\PowerToys\Dashboard">
        <label translate="true">Example dashboard</label>
        <arguments>
            <argument name="enable">false</argument>
            <argument name="template">Jajuma_PowerToys::default_templates/dashboard.phtml</argument>
            <argument name="lazyload">true</argument>
            <argument name="cache_lifetime">86400</argument>
            <argument name="sort_order">0</argument>
            <argument name="acl_resource"></argument>
        </arguments>
    </dashboard>
</powertoys>
